tap "caskroom/fonts"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "hugo"
brew "mongodb"
brew "node"
brew "pipenv"
brew "postgresql", restart_service: true
brew "shfmt"
brew "tmux"
brew "yarn"
brew "dart-lang/dart/dart"
cask "dbeaver-community"
cask "caskroom/fonts/font-hack-nerd-font"