tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "duckdb"
brew "ffmpeg"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "herdr"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "mise"
brew "mole"
brew "qrencode"
brew "r"
brew "redis"
brew "rtk"
brew "tmux"
brew "tokei"
brew "tree"
brew "visidata"
brew "wget"
brew "zsh"

cask "bruno"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "font-fira-code"
cask "keepingyouawake"
cask "keyboardcleantool"
cask "kitty"
cask "ngrok"
cask "rstudio"

npm "@colbymchenry/codegraph"
npm "@earendil-works/pi-coding-agent"