tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "asdf"
brew "sqlite"
brew "ffmpeg"
brew "git"
brew "go"
brew "hub"
brew "jq"
brew "nushell"
brew "redis", restart_service: true
brew "tmux"
brew "wget"
brew "zsh"

cask "font-fira-code"
cask "keepingyouawake"
cask "keyboardcleantool"
cask "ngrok"