[tools]
bun = "latest"
duckdb = "latest"
go = "latest"
java = "latest"
node = "latest"
python = "latest"
ruff = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]
# Tells mise to look for a uv.lock or pyproject.toml 
# and automatically activate the .venv using uv
python.uv_venv_auto = true
