[tools]
bun = "latest"
duckdb = "latest"
go = "latest"
java = "latest"
node = "latest"
"npm:@alibaba-group/open-code-review" = { version = "latest", trust_policy_excludes = "@alibaba-group/open-code-review" }
"npm:@colbymchenry/codegraph" = "latest"
"npm:@google/clasp" = "latest"
"npm:@vue/language-server" = "latest"
"npm:clerk" = "latest"
"npm:netlify-cli" = { version = "latest", trust_policy_excludes = ["@netlify/serverless-functions-api"] }
"npm:oxfmt" = "latest"
"npm:prettier" = "latest"
"npm:typescript-language-server" = "latest"
python = "latest"
ruff = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]
# Tells mise to look for a uv.lock or pyproject.toml 
# and automatically activate the .venv using uv
python.uv_venv_auto = true
